// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jigeusdwsfwstggdngww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZ2V1c2R3c2Z3c3RnZ2RuZ3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NzQwMjAsImV4cCI6MjA1NzA1MDAyMH0.2siRBuB_rN3rKCRVgb8A3ChwSnKipRFafuGW2Cb5ZT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);